### ISSUE TITLE
django-ldapdb .save() is failing?

### ISSUE THREAD

**Issue by JohnTheodore** [jlaine/django-ldapdb#61]
I'm trying to use a django-ldapdb with my little app: ( https://github.com/JohnTheodore/django-ldap/tree/sshkeys/backend_django/sshkeys ). I have a view setup ( localhost:8000/sshkeys ) where it reads an ldap server and gives me the results from my user. Reading seems to work fine, it's writing or .save() that I'm failing on. The results of me trying to .save() are object not found, the log is here for that: https://gist.github.com/anonymous/3029037378b4116ef519

Why does it say object not found, since I just read the object and it does exist?

The ultimate goal is I want to be able to have people manage their own ssh keys in ldap, for passwordless ssh login through ldap.

**Comment by jlaine** [comment]
I did not see the code where you actually save?
