### ISSUE TITLE
ListField behaving bad with project mysql

### ISSUE THREAD

**Issue by alexbarcelo** [jlaine/django-ldapdb#65]
I have a configuration where I am using a default mysql database and a certain ldap backend. I have performed minimal configuration and it works as expected, but the

`./manage.py check`

complains about:

    File "/<...>/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 21, in check_field
      if (field_type.startswith('varchar')  # Look for CharFields...

it seems that by default, MySQL is checking all fields and the `ListField.db_type()` is returning `None`. And, as MySQL module expects a thing like `varchar(200)` or something similar, there is a error.

The production site is up&running, but I cannot perform debug of the application, so I am looking for any workaround or fix. I am not sure if there is some way to avoid MySQL checking the LDAP models, or... don't know. I am a bit lost here.

**Comment by bastiaanraa** [comment]
Django version >= 1.7.2 should fix this (https://code.djangoproject.com/ticket/23761)

**Comment by jlaine** [comment]
I am closing this issue based on Bastiaan's feedback
