### ISSUE TITLE
Support global LDAP options

### ISSUE THREAD

**Issue by dploeger** [jlaine/django-ldapdb#66]
For several reasons, ldap needs to set options *before* any connection to an ldap server is made (for example: disabling ssl certficate checks).

Currently, only CONNECTION_OPTIONS can be set. A list of GLOBAL_OPTIONS would be fine, that would be set before the first connection is made.

**Comment by jlaine** [comment]
I don't understand the point of this : you are simply modifying "ldap" directly, so you might as well put whatever init code you need in your settings.py or whatever is convenient. Adding a proxy API inside django-ldapdb does not add much. Am I missing something?

**Comment by dploeger** [comment]
In my eyes, it is cleaner that way. You don't have to know, which file would be read in what order (which would be important) and you clearly configure it for ldapdb.

BTW: I'm used to that configuration method from other packages like django-auth-ldap.

**Comment by jlaine** [comment]
On the downside you are messing with ldap.* (so ANY ldap connection, whether or not it is managed by django-ldapdb is affected) without making this clear to the user.

**Comment by dploeger** [comment]
Yes, sadly that's true because of the libldap implementation, but it's the only way to work with non-commercial certificates on the server side.

**Comment by dploeger** [comment]
Sorry, @jlaine I just removed my fork with the changes. Are you considering on accepting pull request #67? If not, just close it.

**Comment by jlaine** [comment]
Won't fix for the reasons explained above : you can achieve the same effect directly in your app's code
