### ISSUE TITLE
no such table: LdapManager_ldapuser on POST/Saving of ldap user or group

### ISSUE THREAD

**Issue by KontiSR** [jlaine/django-ldapdb#78]
I'm running a setup with three database sources.

Opening The ldap group directory and opening a specific ldap entry works fine.
Since commit 6930a8d6e67289335d6340ed049558dbddff8c58 I only have the problem with adding new ldap entries. Saving existing now works.

The error message is the same.
OperationalError at /admin/LdapManager/ldapuser/add/
no such table: LdapManager_ldapuser

I'm using ldapdb form within the admin interface. Maybe that's something the issue in combination with multiple databases?

In short it tries to use the default database 'sqlite' to lookup the LdapManager_ldapuser table.
This is part of a self.full_clean() sanity check, where it checks if the value is unique.

Sorry, I can't pinpoint where this is going wrong. There is no ldap reference in the trace.

Any idea how to get around this?

Settings:

		DATABASES = {
		 'default': {
			'ENGINE': 'django.db.backends.sqlite3',
			...
		 },
		 'serviceCatDb' : {
			"ENGINE" : 'ibm_db_django',
			...
		 },
		 'ldap': {
			'ENGINE': 'ldapdb.backends.ldap',
			...
		  }
		 }

Model:

    class AccessGroup(ldapdb.models.Model):
    '''
    Class for representing ldap access group entry.
    '''
    class Meta:
        managed = False
        verbose_name = "AccessGroup"
        
    base_dn = "ou=Groups,dc=sview,dc=domain,dc=nl"
    object_classes = ['groupOfNames','top']
    
    name = CharField(db_column='cn', max_length=200, primary_key=True)
    members = ListField(db_column='member', default=[])
    description = CharField(db_column='description',blank=True,null=True,max_length=200)
    
    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name

Admin:

    class MultiDBModelAdmin(admin.ModelAdmin):
    # A handy constant for the name of the alternate database.
    using = 'ldap'
    
    def save_model(self, request, obj, form, change):
        # Tell Django to save objects to the 'other' database.
        obj.save(using=self.using)
 
    def delete_model(self, request, obj):
        # Tell Django to delete objects from the 'other' database
        obj.delete(using=self.using)
 
    def get_queryset(self, request):
        # Tell Django to look for objects on the 'other' database.
        return super(MultiDBModelAdmin, self).get_queryset(request).using(self.using)
 
    def formfield_for_foreignkey(self, db_field, request=None, **kwargs):
        # Tell Django to populate ForeignKey widgets using a query
        # on the 'other' database.
        return super(MultiDBModelAdmin, self).formfield_for_foreignkey(db_field, request=request, using=self.using, **kwargs)
 
    def formfield_for_manytomany(self, db_field, request=None, **kwargs):
        # Tell Django to populate ManyToMany widgets using a query
        # on the 'other' database.
        return super(MultiDBModelAdmin, self).formfield_for_manytomany(db_field, request=request, using=self.using, **kwargs)

    class AccessGroupAdmin(MultiDBModelAdmin):
        class Meta:
            model = AccessGroup
    
        form = LdapGroupForm    
        list_display = ('name','members','description')
        search_fields = ['name']
        exclude = ['dn']

Don't think the form is very relevant.

	class LdapUserAdmin(MultiDBModelAdmin):
		class Meta:
			model = LdapUser
			
		list_display = ('userid', 'common_name', 'surname','display_name','mail')
		search_fields = ['userid','common_name','surname','display_name','mail']
		exclude = ['dn']

Full Trace:
	Environment:

	Request Method: POST
	Request URL: http://localhost:8080/admin/LdapManager/ldapuser/add/

	Django Version: 1.7
	Python Version: 2.7.9
	Installed Applications:
	('django.contrib.admin',
	 'django.contrib.auth',
	 'django.contrib.contenttypes',
	 'django.contrib.sessions',
	 'django.contrib.messages',
	 'django.contrib.staticfiles',
	 'ServiceCatalogue',
	 'LdapManager')
	Installed Middleware:
	('django.contrib.sessions.middleware.SessionMiddleware',
	 'django.middleware.common.CommonMiddleware',
	 'django.middleware.csrf.CsrfViewMiddleware',
	 'django.contrib.auth.middleware.AuthenticationMiddleware',
	 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	 'django.contrib.messages.middleware.MessageMiddleware',
	 'django.middleware.clickjacking.XFrameOptionsMiddleware')

	Traceback:
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\core\handlers\base.py" in get_response
	  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\contrib\admin\options.py" in wrapper
	  567.                 return self.admin_site.admin_view(view)(*args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\utils\decorators.py" in _wrapped_view
	  105.                     response = view_func(request, *args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\views\decorators\cache.py" in _wrapped_view_func
	  52.         response = view_func(request, *args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\contrib\admin\sites.py" in inner
	  204.             return view(request, *args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\contrib\admin\options.py" in add_view
	  1437.         return self.changeform_view(request, None, form_url, extra_context)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\utils\decorators.py" in _wrapper
	  29.             return bound_func(*args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\utils\decorators.py" in _wrapped_view
	  105.                     response = view_func(request, *args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\utils\decorators.py" in bound_func
	  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\transaction.py" in inner
	  394.                 return func(*args, **kwargs)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\contrib\admin\options.py" in changeform_view
	  1380.             if form.is_valid():
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\forms\forms.py" in is_valid
	  162.         return self.is_bound and not bool(self.errors)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\forms\forms.py" in errors
	  154.             self.full_clean()
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\forms\forms.py" in full_clean
	  355.         self._post_clean()
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\forms\models.py" in _post_clean
	  430.             self.validate_unique()
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\forms\models.py" in validate_unique
	  439.             self.instance.validate_unique(exclude=exclude)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\base.py" in validate_unique
	  799.         errors = self._perform_unique_checks(unique_checks)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\base.py" in _perform_unique_checks
	  894.             if qs.exists():
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\query.py" in exists
	  606.             return self.query.has_results(using=self.db)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\sql\query.py" in has_results
	  445.         return compiler.has_results()
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\sql\compiler.py" in has_results
	  757.         return bool(self.execute_sql(SINGLE))
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\models\sql\compiler.py" in execute_sql
	  786.             cursor.execute(sql, params)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\backends\utils.py" in execute
	  81.             return super(CursorDebugWrapper, self).execute(sql, params)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\backends\utils.py" in execute
	  65.                 return self.cursor.execute(sql, params)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\utils.py" in __exit__
	  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\backends\utils.py" in execute
	  65.                 return self.cursor.execute(sql, params)
	File "D:\Users\user\.virtualenv\BSM\lib\site-packages\django\db\backends\sqlite3\base.py" in execute
	  485.         return Database.Cursor.execute(self, query, params)

	Exception Type: OperationalError at /admin/LdapManager/ldapuser/add/
	Exception Value: no such table: LdapManager_ldapuser

**Comment by aprilmay** [comment]
I don't think Django makes any use of the "using = 'ldap'" statement in the ModelAdmin definition.

Did you add "DATABASE_ROUTERS = ['ldapdb.router.Router']" in your settings?

**Comment by KontiSR** [comment]
Yes i'm also getting that idea. Is there anyway around that? Maybe some
overwrite?

Yes i put that in my settings. Really dont know if it has any effect?
Op 26 jul. 2015 9:14 AM schreef "Philippe May" <notifications@github.com>:

**Comment by jlaine** [comment]
On 07/27/2015 12:09 AM, Rogier wrote:
> Yes i'm also getting that idea. Is there anyway around that? Maybe some
> overwrite?
>
> Yes i put that in my settings. Really dont know if it has any effect?

It absolutely should have an effect:

https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-DATABASE_ROUTERS

**Comment by KontiSR** [comment]
Well I've finally got it to work. The problem was the order of the routers.
This works:
DATABASE_ROUTERS = ['ldapdb.router.Router',
                    'Db2App.db2approuter.Db2appRouter', 
                    'projectname.defaultrouter.DefaultRouter']

This gave the error as described:
DATABASE_ROUTERS = ['projectname.defaultrouter.DefaultRouter',
                    'Db2App.db2approuter.Db2appRouter', 
                    'ldapdb.router.Router']

So I don't know if I stumbled on a django or ldapdb bug? At least for me it's working now!

**Comment by aprilmay** [comment]
Good you found the problem.
It's not a bug:
https://docs.djangoproject.com/en/1.8/topics/db/multi-db/#using-routers

**Comment by KontiSR** [comment]
It might not be a bug in the code. But then it's a bug in documentation. Because even now when I know what to look for, and have the documentation in front of me, it's still not totally clear why it's working like this.

I agree, i'm still a beginner in django, and also pretty much novice in python alround. But I can't image i'm the only one spending allot of hours on an issue like this.

**Comment by aprilmay** [comment]
The doc says: "Django then tries each router in turn until a database suggestion can be found". Maybe not very explicit, but quite precise actually once you figure out what the "in turn" formulation means.

Off topic: that said, i never really liked the way Django implemented the multiple databases routers, and other design choices. Django as a whole has a monolithic approach first that works well out of the box in simple cases, and extended little by little. But, one needs to dig in the code and class hierarchy so much for doing "simple" things: eg querysets, forms, generic views, can be actually a pain to deal with. In other words, for me, Django is not what it claims anymore: "The web framework for perfectionists with deadlines".
